//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YakuzaUlsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int idTarjeta { get; set; }
        public int idTipo { get; set; }
        public int idConsumidor { get; set; }
        public string numeroTarjeta { get; set; }
        public string bancoTarjeta { get; set; }
    
        public virtual Consumidor Consumidor { get; set; }
        public virtual TipoDeTarjeta TipoDeTarjeta { get; set; }
    }
}
